### ISSUE TITLE
Reset sur le CAN

### ISSUE THREAD

**Issue by 42Max42** [PhenixRobotik/ivegotdapower-elec#3]
corriger le problème de reset

**Comment by Salamandar** [comment]
Mais alors on fait quoi ? On ne le relie pas du tout ? On met des diodes ?
Je suis d'avis comme on l'avait déjà évoqué d'avoir un message de soft-reset sur le CAN qui doit être interprété par le firmware.

**Comment by Salamandar** [comment]
Backported the fix with 0896a17
